### ISSUE TITLE
Fix the wack behavior of placing blocks in enemy core range

### ISSUE THREAD

**Issue by BalaM314** [BalaM314/mindustry-client#2]
it's just weird
also add a yellow highlight to blocks that are in enemy ground turret range

**Comment by sbxte** [comment]
I think this is a zxtej thing so that you can queue plans in there and build them as soon as the core is converted to our team's. Imo I like it, very good for capturing cores whilst having enemies still threaten it (either in turret range or lots of enemies go by) simply because I can queue lancers or tsunamis

**Comment by BalaM314** [comment]
i think we fixed this
